name: Build and Release MSI

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.1)'
        required: false
        type: string

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission to Gradle wrapper
        run: |
          git config --global core.autocrlf false
          ./gradlew --version

      - name: Package MSI
        run: ./gradlew packageApp

      - name: Find MSI
        id: find-msi
        run: |
          $msi = Get-ChildItem -Recurse -Filter "*.msi" | Select-Object -First 1
          
          $msiPath = $msi.FullName -replace '\\', '/'
          echo "MSI_PATH=$msiPath" >> $env:GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag || github.ref_name }}
          files: ${{ env.MSI_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}